---
title: "Welcome!"
---

## What is this?

This is a collection of code that has been developed, reused, and refined by the Analytics for Australian Grains Industry (AAGI) network. The kind of code that often lives in personal folders but proves useful again and again in projects.

Code here is shared to support collaboration, consistency, and make our work easier. Not everything is polished or packaged. The aim is by making code available, we can start to improve it as a community. 

## Who is the database for? 

This resource is created for AAGI Biometricians in mind.

It may be useful for other use cases in different fields. If this is the case, we encourage you to reach out to the code custodian for more context and collaboration. 

## What kind of code will you find?

You’ll find a mix of materials, including ultility functions for:

- data processing and checking

- data visualisation

- model diagnostics 

- computing summary statistics

- format outputs for reorting

Some contributions are shared as-is, while others are more formal software packages with their own governance. Each entry clearly states its level of maturity and intended use.

> [Explore the database](database/dtable.qmd)

## How can I contribute?

Contributing is intentionally lightweight. You can:

- Share a function you’ve reused in multiple projects

- Make improvements by working on bug fixes to existing code

- Contribute to documentation with examples or data

Code does not need to be perfect or fully documented to be useful. The database team can help with that. [Insert easy method here] Often clear context and basic attribution is more than enough. 

> [Learn more on how you can contribute](database/usage.qmd) 

##  How should I use the code?

This resource is sustained by recognition and collaboration. All code is shared under clear licenses and version control, so you can:

- Reuse it directly in your own work

- Adapt it to suit your project needs

- Contribute improvements if you wish

> [Learn more how to use shared code responsibly](database/usage.qmd)